# tasks for msg-service
- name: user for msg-service
  include_role:
    name: user
  vars:
    user_name: "{{ app_user | default('msg-service') }}"
    user_group: "{{ app_group | default('msg-service') }}"

- name: user for msg-service
  become: yes
  user:
    name: msg_user.user
    append: yes

- name: dir
  become: yes
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ app_user | default('msg-service') }}"
    group: "{{ app_group | default('msg-service') }}"
    recurse: yes
  with_items:
    - "{{ app_home }}/bin"
    - "{{ app_home }}/conf"

- name: download
  become: yes
  get_url:
    url: https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/msg-service/msg-server
    dest: "{{ app_home | default('/opt/msg-service') }}/bin"
    mode: 0755

- name: Copy configuration file
  become: yes
  template:
    src: msg-service.config
    dest: "{{ app_home}}/conf/msg-server.conf"
    owner: "{{ app_user | default('msg-service') }}"
    group: "{{ app_group | default('msg-service') }}"
    mode: 0644
  notify:
    - service_start

- name: copy sysd
  become: yes
  template:
    src: msg-service.service
    dest: "{{ sysd }}/msg-service.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - service_start
    - Creating custom fact

- name: running
  become: yes
  systemd:
    name: msg-service.service
    state: started
    enabled: yes
  notify:
    - service_start
