- name: installing repo
  become: yes
  yum:
    name: https://repo.mysql.com//mysql80-community-release-el7-3.noarch.rpm
    state: present

- name: installing repo
  become: yes
  yum:
    name:
      - mysql-community-server
      - mysql-community-devel
    state: present

# Just shell command for initilasation of db
- name: init
  become: yes
  command: mysqld --initialize-insecure --user=mysql
  when: ansible_local.mysql is undefined or not ansible_local.mysql.base_initialized
  notify:
    - mysql_fact

- name: running
  become: yes
  systemd:
    name: mysqld
    state: started
    enabled: yes
  notify:
    - restart mysql

# Unfortunately mysql_query is not in the list of ansible default modules
# it's a community module and it's not available by default
- name: password establishing
  become: yes
  shell: set -o pipefail && echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ root_password | mandatory }}';" | mysql -u root --skip-password
  when: ansible_local.mysql is undefined or not ansible_local.mysql.root_passw_established
  notify:
    - mysql_fact


