---
# tasks file for mysql_db_user

- name: db user
  become: yes
  mysql_user:
    name: "{{ mysql_user | default('ayoursh') }}"
    password: "{{ mysql_password | default('pAssw0rd') }}"
    priv: "{{ mysql_user_pivileges | default('*.*:ALL') }}"
    state: present
  when: ansible_local.mysql_user_{{ mysql_user }} is undefined or not ansible_local.mysql_user_{{ mysql_user }}.exist
  notify:
    - mysql_user_fact

- name: db
  become: yes
  mysql_db:
    name: "{{ mysql_db_user_database | default('production') }}"
    state: present
    login_user: "{{ mysql_user | default('yoursh') }}"
    login_password: "{{ mysql_password | default('pAssw0rd') }}"
  when: ansible_local.mysql_db_{{ mysql_db_user_database }} is undefined or not ansible_local.mysql_db_{{ mysql_db_user_database }}.exist
  notify:
    - mysql_db_fact
