- name: user for mysql-check
  include_role:
    name: user
  vars:
    user_name: "{{ mysql_check_user | default('mysql-check') }}"
    user_group: "{{ mysql_check_group | default('mysql-check') }}"
  when: ansible_local.mysql_check is undefined or not ansible_local.mysql_check.USER_INIT

- name: dir
  become: yes
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ mysql_check_user | default('mysql-check') }}"
    group: "{{ mysql_check_group | default('mysql-check') }}"
    recurse: yes
  with_items:
    - "{{ mysql_check_dir }}/bin"
    - "{{ mysql_check_dir }}/conf"

- name: Download file
  become: yes
  get_url:
    url: https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/mysql-check/mysql-check
    dest: "{{ mysql_check_dir }}/bin"
    owner: "{{ mysql_check_user | default('mysql-check') }}"
    group: "{{ mysql_check_group | default('mysql-check') }}"
    mode: 0755

- name: copy templates
  become: yes
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  loop:
    - { src: mysql-check.config,
        dest: "{{ mysql_check_dir }}/conf/mysql-check.conf",
        owner: "{{ mysql_check_user | default('mysql-check') }}",
        group: "{{ mysql_check_group | default('mysql-check') }}",
        mode: "0644" }
    - { src: mysql-check.service,
        dest: "{{ sysd }}/mysql-check.service",
        owner: root,
        group: root,
        mode: "0644" }
  notify:
    - restart mysql-check
    - mysql_check_fact

- name: mysql_check_port_fact
  set_fact:
     mysql_check_port: "{{ mysql_check_port }}"

- name: Check service for running status
  become: yes
  systemd:
    name: mysql-check.service
    state: started
    enabled: yes
  notify:
    - restart mysql-check
